### ISSUE TITLE
Error on edit mode: MarkdownToHTML not defined

### ISSUE THREAD

**Issue by DirtyF** [tinalabs/next-git-starter#1]
## Issue

Given I'm using the [default preview from the documentation](https://tina.io/guides/tina-cloud/existing-site/page-preview/)
When I load a post in edit mode from http://localhost:3000/admin/posts/hello-world
Then I get 2 errors about `ReferenceError: markdownToHtml is not defined`
And the body is not shown on the page

<img width="944" alt="CleanShot 2021-05-13 at 16 24 31@2x" src="https://user-images.githubusercontent.com/103008/118139583-ca7ea400-b407-11eb-83e2-fcfdeae904dc.png">

## Expected
No errors and I can see the preview of the HTML on the page

/cc @tinalabs/tinacms-maintainers

**Comment by jamespohalloran** [comment]
Issue is in the documentation. Created PR here: https://github.com/tinacms/tinacms.org/pull/864
